workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

############################################
######## Development Environment ###########
############################################
develop:
  variables:
    IMAGE_TAG: latest
  trigger:
    include: .gitlab-ci.d/develop.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always



###########################################
######## Sandbox Environment ##############
###########################################
sandbox:
  variables:
    IMAGE_TAG: latest
  trigger:
    include: .gitlab-ci.d/sandbox.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "sandbox"
      when: always

###########################################
######## Production Environment ###########
###########################################
production:
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  trigger:
    include: .gitlab-ci.d/production.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG =~ /\d+\.\d+\.\d+\-p$/
      when: always
